DROP TABLE `surveyService`.`answer`, 
			`surveyService`.`answer_selection`, 
			`surveyService`.`answer_section`,
	        `surveyService`.`question`, 
	        `surveyService`.`question_choices`, 
	        `surveyService`.`question_ranking_choices`, 
	        `surveyService`.`question_section`, 
	        `surveyService`.`question_section_questions`, 
	        `surveyService`.`survey_chart`, 
	        `surveyService`.`survey_chart_point`, 
	        `surveyService`.`survey_chart_serie`, 
	        `surveyService`.`survey_chart_xcoordinate`, 
	        `surveyService`.`survey_questions`, 
	        `surveyService`.`survey_responses`,
	        `surveyService`.`survey`;